### PR TITLE
Add template

### PR DESCRIPTION
**Pull request by dryewo**
A Leiningen template for Zalando's own projects.

### CODE REVIEW

**Comment by dryewo** [comment]
Beta available here: https://clojars.org/friboo-ext-zalando/lein-template/versions/2.0.0-beta1

**Comment by dryewo** [comment]
👍

**Comment by dryewo** [comment]
https://clojars.org/friboo-ext-zalando/lein-template/versions/2.0.0-beta2

    $ lein new friboo-ext-zalando com.example/foo-bar --template-version 2.0.0-beta2

**Comment by harti2006** [comment]
:+1:

**Comment by dryewo** [comment]
👍

**Pull request merged**
